### ISSUE TITLE
ERROR  Cannot restart nuxt:  Cannot find module 'nuxt'

### ISSUE THREAD

**Issue by lumixraku** [mightyjiao/sketch-editor#9]
全部依赖都装上了, 却还是提示 nuxt 找不到.  Any suggestions? 
 node 18.17.1
 npm 9.6.7
 
 skeditor on  main [?] via ⬢ v18.17.1
➜
 ERROR  Cannot start nuxt:  Cannot find module 'nuxt'
Require stack:
- /Users/lilin/repos/Others/skeditor/index.js

  Require stack:
  - index.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
  at Function.resolve (node:internal/modules/cjs/helpers:127:19)
  at Function._resolve [as resolve] (node_modules/.pnpm/registry.npmmirror.com+jiti@1.21.0/node_modules/jiti/dist/jiti.js:1:251148)
  at resolveModule (node_modules/.pnpm/registry.npmmirror.com+@nuxt+kit-edge@3.0.0-rc.9-27703329.537338f/node_modules/@nuxt/kit-edge/dist/index.mjs:254:29)
  at importModule (node_modules/.pnpm/registry.npmmirror.com+@nuxt+kit-edge@3.0.0-rc.9-27703329.537338f/node_modules/@nuxt/kit-edge/dist/index.mjs:282:24)
  at loadNuxt (node_modules/.pnpm/registry.npmmirror.com+@nuxt+kit-edge@3.0.0-rc.9-27703329.537338f/node_modules/@nuxt/kit-edge/dist/index.mjs:713:43)
  at async load (node_modules/.pnpm/registry.npmmirror.com+nuxi-edge@3.0.0-rc.9-27703329.537338f/node_modules/nuxi-edge/dist/chunks/dev.mjs:6767:23)
  at async Object.invoke (node_modules/.pnpm/registry.npmmirror.com+nuxi-edge@3.0.0-rc.9-27703329.537338f/node_modules/nuxi-edge/dist/chunks/dev.mjs:6826:5)
  at async _main (node_modules/.pnpm/registry.npmmirror.com+nuxi-edge@3.0.0-rc.9-27703329.537338f/node_modules/nuxi-edge/dist/cli.mjs:50:20)

**Comment by lumixraku** [comment]
清空再装突然好了
